# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  NEON_PROJECT_ID: ${{ vars.NEON_PROJECT_ID }}
  NEXT_PUBLIC_FACEBOOK_APP_ID: ${{ vars.NEXT_PUBLIC_FACEBOOK_APP_ID }}
  NEXT_PUBLIC_FACEBOOK_PIXEL_ID: ${{ vars.NEXT_PUBLIC_FACEBOOK_PIXEL_ID }}
  NEXT_PUBLIC_GOOGLE_ADS_ID: ${{ vars.NEXT_PUBLIC_GOOGLE_ADS_ID }}
  NEXT_PUBLIC_GOOGLE_OPTIMIZE_ID: ${{ vars.NEXT_PUBLIC_GOOGLE_OPTIMIZE_ID }}
  NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID: ${{ vars.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID }}
  NEXT_PUBLIC_IG_USER: ${{ vars.NEXT_PUBLIC_IG_USER }}
  NEXT_PUBLIC_SITE_LOGO: ${{ vars.NEXT_PUBLIC_SITE_LOGO }}
  NEXT_PUBLIC_SITE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}

  BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
  EDGE_CONFIG: ${{ secrets.EDGE_CONFIG }}
  KV_REST_API_READ_ONLY_TOKEN: ${{ secrets.KV_REST_API_READ_ONLY_TOKEN }}
  KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
  KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
  KV_URL: ${{ secrets.KV_URL }}
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
  NEXT_PUBLIC_IG_PSWD: ${{ secrets.NEXT_PUBLIC_IG_PSWD }}
  POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
  POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build --if-present
      - name: Prettier Check
        run: npm run prettier:check
      - name: Type Check
        run: npm run typecheck
      - name: Lint JS
        run: npm run lint
      - name: Lint MD
        run: npm run mdlint
      - name: Jest Testing
        run: npm run test:ci
      - name: Vitest Testing
        run: npm run test:vitest:ci
      - name: Storybook Build
        run: npm run build-storybook
